name: ci

on: push

jobs:
  test:
    name: test tape-moonbeam on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '15'

      - run: |
          npm install
          npm test